version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./frontend/src:/catering/frontend/src
      - ./frontend/public:/catering/frontend/public
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=http://backend:5000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - ./backend
    environment:
      - MONGO_CONNSTRING=mongodb+srv://luna:luna@cluster0.bktgnyb.mongodb.net/?retryWrites=true&w=majority
      - FRONTEND=http://frontend:3000
      - MONGO_INITDB_ROOT_USERNAME=luna
      - MONGO_INITDB_ROOT_PASSWORD=luna

networks:
  mern-network:
    driver: bridge
